server:
  #这里是因为nginx占用了8080端口得改一下,访问服务器得是8081 (nginx一定要放在非中文)
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.200.130
    port: 6379
    password: qwer123456qaz.
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    # JSON处理时忽略非空字段
    default-property-inclusion: non_null
mybatis-plus:
  # 别名扫描包
  type-aliases-package: com.hmdp.entity
logging:
  level:
    com.hmdp: debug